name: ictproject
description: "ICT동남권이노베이션 프로젝트"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  envied: ^0.5.4+1
  intl: ^0.19.0

  cupertino_icons: ^1.0.0
  dart_openai: ^5.1.0

  http: ^1.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
  - assets/config/.env

    #환경 요소
  - assets/images/logo.png
  - assets/images/o1logo.png
  - assets/images/watchbox.png